language: cpp

sudo: required

notifications:
  email: false

branches:
  only:
    - master
    - stable

before_install:
  - sudo apt-get update -qq
  - mkdir build
  - make download-all
  - sudo ./install_prereqs.sh ubuntu
  - make

script:
  - cd drake/pod-build
  - ctest -j 1 -D Experimental -C $BUILD_TYPE --output-on-failure --timeout 1000 --track Continuous

# The compiler and env:matrix options create an matrix of build configurations (gcc + Release, gcc + Debug, clang + Release, clang + Debug)

compiler:
  - gcc
  - clang

python:
  - '2.7'

env:
  global:
    - CMAKE_FLAGS="-DWITH_SPOTLESS:BOOL=OFF -DWITH_LIBBOT:BOOL=ON -DWITH_GTK:BOOL=ON -DWITH_DIRECTOR:BOOL=ON -DWITH_IRIS:BOOL=ON-DWITH_OCTOMAP:BOOL=ON -DWITH_MOSEK:BOOL=ON -DWITH_AVL:BOOL=ON -DWITH_XFOIL:BOOL=ON"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release