language: cpp

sudo: required

notification:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install gcc-4.8 g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir build
  - make download-all
  - sudo ./install_prereqs.sh ubuntu

script:
  - make
  - cd drake/pod-build
  - ctest -j 1 -D Experimental -C $BUILD_TYPE --output-on-failure --timeout 1000 --track Continuous

# The compiler and env:matrix options create an matrix of build configurations (gcc + Release, gcc + Debug, clang + Release, clang + Debug)

compiler:
  - gcc
  - clang

env:
  global:
    - CMAKE_FLAGS="-DWITH_SPOTLESS:BOOL=OFF"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release