version: 1.0.{build}
os: Visual Studio 2015
clone_depth: 5
install:
  # todo: get pkg-config from sourceforge, and unpack it
  - ps: (new-object net.webclient).DownloadFile('https://dl.dropboxusercontent.com/u/3432353/pkg-config.exe', 'c:\pkg-config.exe')
environment:
  matrix:      # todo: pass in WITH_* options to enable more externals
    # 64-bit build
    - CMAKE_FLAGS: -G "Visual Studio 14 2015 Win64"
    # 32-bit build
    - CMAKE_FLAGS: -G "Visual Studio 14 2015"
before_build:
  - cmd: set PATH=%PATH%;c:\;c:\projects\drake\build\bin;c:\projects\drake\build\lib;c:\projects\drake\drake\pod-build\lib\Release
  - cmd: PATH
  - cmd: cmake -E make_directory pod-build
  - cmd: cd pod-build && cmake .. %CMAKE_FLAGS% && cd ..
  # note: this is building as 32-bit right now.  could add the -G arguments above to build 64-bit
build_script:
  - cmd: cmake --build pod-build --config Release
test_script:
  - cmd: cd drake\pod-build
  - cmd: cmake -DBUILDNAME="appveyor-win32" .. || true
  - cmd: ctest -j 1 -M Experimental -T Test -T Submit -C Release --output-on-failure --timeout 1000 --track Continuous
