config:
  # Simulation duration in seconds.
  simulation_time: 10.0
  # Config for `class Simulator`.
  simulator_config:
    integration_scheme: "cenic"
    accuracy: 1e-3
    max_step_size: 0.1
    use_error_control: true
    publish_every_time_step: true
  # Config for `class MultibodyPlant`.
  plant_config:
    # If time_step > 0, the fixed-time step period (in seconds) of discrete
    # updates for the plant (modeled as a discrete system).
    #
    # If time_step = 0, the plant is modeled as a continuous system and no
    # contact forces are displayed.
    time_step: 0.0
    # Use hydro contact. (Alternatively, you can use "point".)
    contact_model: "hydroelastic"
    # Stiction tolerance [m/s].
    stiction_tolerance: 1.0e-4
    # Discrete contact solver. Options are: "tamsi", "sap", "lagged", "similar".
    discrete_contact_approximation: "lagged"
    # SAP near rigid threshold.
    sap_near_rigid_threshold: 1.0
  # Config for `class SceneGraph`.
  scene_graph_config:
    default_proximity_properties:
      # For hydro contact.
      compliance_type: "compliant"
      resolution_hint: 0.01
  # Adds visualization; to disable it, delete this entire stanza.
  visualization_config:
    # We don't want viz to interfere with error-control. Therefore we use a
    # large viz period so that publish_every_time_step controls whether to
    # publish (at the end of each integrator step) or not.
    publish_period: 1e9
    # Whether to visualize forces (true) or not (false).
    publish_contacts: true
    # Whether to visualize collision geometry (true) or not (false).
    publish_proximity: false
  # Config for `class IcfSolver`. Only used when integration_scheme is "cenic".
  icf_solver_config:
    # Main solver tolerance in fixed-step mode; minimum scaled tolerance with
    # error control.
    min_tolerance: 1e-8
    # Whether to reuse the Hessian factorization between iterations.
    enable_hessian_reuse: false
    # Maximum number of iterations before re-computing the Hessian.
    hessian_reuse_target_iterations: 10
    # Whether to use dense algebra in the ICF solver.
    use_dense_algebra: false
    # Tolerance for the exact line search performed by the convex integrator.
    linesearch_tolerance: 1e-8
    # Maximum line search step size for the convex integrator (Î±_max).
    alpha_max: 1.0
    # Whether to print statistics to the console.
    print_solver_stats: false
  # Config for the arm's controller.
  controller_config:
    # Controller type: "pid", "inverse_dynamics", or "joint_stiffness".
    # When plant_config.time_step > 0, only "pid" is valid.
    type: "joint_stiffness"
    # Controller gains (proportional, integral, derivative).
    kp: 1e3
    ki: 0
    kd: 1e3
  # Whether to include a box to hold.
  manipuland: true
