blank_issues_enabled: true
contact_links:
  - name: Questions, Requests for Help, Build or Installation Problems, Troubleshooting
    url: https://github.com/RobotLocomotion/drake/discussions/new/choose
    about: Please ask and answer these kinds of questions using Discussions, not Issues.
