# WARNING for Drake Developers: If you change this file, you must regenerate
# the "locked" pdm output file via:
#
#     tools/workspace/python/venv_upgrade
#
# This file primarily defines the set of Python dependencies that are used by
# Drake in various ways and are managed by tools/workspace/python/venv_sync.
# It is the responsibility of tools/workspace/python/repository.bzl to decide
# which dependency groups need to be installed.

[project]
name = "drake"
# When changing this, see drake/tools/workspace/python/README.md.
requires-python = ">=3.10"

# Dependencies needed to build Drake.
dependencies = [
    "ipywidgets",
    "matplotlib",
    "notebook",
    "numpy",
    "Pillow",
    "pydot",
    "PyYAML",
]

[dependency-groups]
# (Additional) dependencies needed to run Drake's tests.
test = [
    "flask",
    "six",
    "u-msgpack-python",
    "websockets",
]
# (Additional) dependencies needed to build a Drake wheel.
wheel = [
    "auditwheel; sys_platform == 'linux'",
    "build",
    "delocate; sys_platform == 'darwin'",
    "wheel; sys_platform == 'darwin'",
]

[tool.pdm]
distribution = false
