config:
  # Simulation duration in seconds.
  simulation_time: 10.0
  # Config for `class Simulator`.
  simulator_config:
    integration_scheme: "cenic"
    accuracy: 1e-3
    max_step_size: 0.1
    use_error_control: true
    publish_every_time_step: true
  # Config for `class MultibodyPlant`.
  plant_config:
    # If time_step > 0, the fixed-time step period (in seconds) of discrete
    # updates for the plant (modeled as a discrete system).
    #
    # If time_step = 0, the plant is modeled as a continuous system and no
    # contact forces are displayed.
    time_step: 0.0
    # Use point contact. (Alternatively, you can use "hydroelastic".)
    contact_model: "point"
    # Stiction tolerance [m/s].
    stiction_tolerance: 1.0e-4
    # Discrete contact solver. Options are: "tamsi", "sap", "lagged", "similar".
    discrete_contact_approximation: "lagged"
    # SAP near rigid threshold.
    sap_near_rigid_threshold: 1.0
  # Config for `class SceneGraph`.
  scene_graph_config:
    default_proximity_properties:
      # N.B. Certain objects will opt-in to "rigid" on a one-by-one basis.
      compliance_type: compliant
      # Material stiffness [Pa].
      hydroelastic_modulus: 1.0e7
      # Resolution hint for the spheres [m].
      resolution_hint: 0.02
      # Friction [unitless].
      dynamic_friction: 0.5
      static_friction: 0.5
      # Hunt & Crossley dissipation [s/m].
      hunt_crossley_dissipation: 10.0
      # Dissipation time constant [s].
      relaxation_time: 0.01
      # Material stiffness [N/m].
      point_stiffness: 1.0e5
  # Adds visualization; to disable it, delete this entire stanza.
  visualization_config:
    # We don't want viz to interfere with error-control. Therefore we use a
    # large viz period so that publish_every_time_step controls whether to
    # publish (at the end of each integrator step) or not.
    publish_period: 1e9
    # Whether to visualize forces (true) or not (false).
    publish_contacts: false
    # Whether to visualize collision geometry (true) or not (false).
    publish_proximity: false
  # Config for `class IcfSolver`. Only used when integration_scheme is "cenic".
  icf_solver_config:
    # Main solver tolerance in fixed-step mode; minimum scaled tolerance with
    # error control.
    min_tolerance: 1e-8
    # Whether to reuse the Hessian factorization between iterations.
    enable_hessian_reuse: false
    # Maximum number of iterations before re-computing the Hessian.
    hessian_reuse_target_iterations: 10
    # Whether to use dense algebra in the ICF solver.
    use_dense_algebra: false
    # Tolerance for the exact line search performed by the convex integrator.
    linesearch_tolerance: 1e-8
    # Maximum line search step size for the convex integrator (α_max).
    alpha_max: 1.0
    # Whether to print statistics to the console.
    print_solver_stats: false
  clutter_config:
    # Physical parameters.
    # - The density of all objects, in kg/m³.
    density: 1000.0
    # Contact geometry parameters.
    # - Emulate multicontact by adding spheres to the faces of box geometries.
    emulate_box_multicontact: true
    # - Multi-contact emulation. We place num_sphere x num_spheres_per_face on
    #   each box face, when emulate_box_multicontact = true.
    num_spheres_per_face: 3
    # - Enable box vs. box contact.
    enable_box_box_collision: false
    # - Adds collision points at the corners of each box.
    add_box_corners: false
    # Scenario parameters.
    # - Number of piles (1-4).
    num_piles: 4 
    # - Number of object per pile.
    objects_per_pile: 5
    # - Initial distance between objects in the pile.
    dz: 0.15
    # - Multiplicative factor to generate the pile.
    scale_factor: 1.0
    # Adds wall of a sink model.
    add_sink_walls: true
    # - Make some of the objects boxes.
    enable_boxes: true
    # - Use slight random offsets in initial positions.
    random_offsets: true
